# Generated by Django 4.2.5 on 2023-09-21 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, help_text='Marque se a tarefa está concluída.'),
        ),
        migrations.AddField(
            model_name='task',
            name='disciplines',
            field=models.ManyToManyField(help_text='Selecione as disciplinas associadas à tarefa.', related_name='tasks', to='discipline.discipline'),
        ),
        migrations.AddField(
            model_name='task',
            name='student',
            field=models.ForeignKey(default=1, help_text='Selecione o estudante para quem a tarefa está atribuída.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='discipline.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discipline',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a disciplina foi criada.'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='description',
            field=models.CharField(help_text='Digite uma breve descrição da disciplina.', max_length=255),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(help_text='Digite o nome da disciplina.', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o estudante foi criado.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(help_text='Digite o endereço de e-mail do estudante.', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='Digite o nome do estudante.', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a tarefa foi criada.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='delivery_date',
            field=models.DateField(help_text='Digite a data de entrega da tarefa.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(help_text='Digite uma breve descrição da tarefa.', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Digite o título da tarefa.', max_length=255),
        ),
    ]
