# Generated by Django 4.2.5 on 2023-09-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0002_task_completed_task_disciplines_task_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='delivery_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
