# Generated by Django 4.2.5 on 2023-09-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0003_alter_task_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
